server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: auth-user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8085/realms/cgi-flow}
  datasource:
    url: ${AUTH_DATABASE_URL:jdbc:postgresql://localhost:15432/cgi_flow_auth}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true

security:
  dev-admin-bypass: ${SECURITY_DEV_ADMIN_BYPASS:true}
  jwt:
    audience: ${KEYCLOAK_AUDIENCE:cgi-flow-api}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8085}
  realm: ${KEYCLOAK_REALM:cgi-flow}
  admin-realm: ${KEYCLOAK_ADMIN_REALM:master}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
