server:
  port: 8081

spring:
  application:
    name: auth-user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cgi_flow_auth
    username: postgres
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
