CREATE TABLE planning_agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE planning_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(32) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    paid_hours INTEGER NOT NULL DEFAULT 8,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_planning_shifts_category CHECK (category IN ('OPENING', 'CLOSING'))
);

CREATE TABLE agent_unavailability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL REFERENCES planning_agents(id),
    unavailable_date DATE NOT NULL,
    reason VARCHAR(255) NOT NULL,
    CONSTRAINT uk_agent_unavailability_day UNIQUE (agent_id, unavailable_date)
);

CREATE TABLE planning_weeks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start_date DATE NOT NULL UNIQUE,
    week_end_date DATE NOT NULL,
    status VARCHAR(32) NOT NULL,
    generated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_planning_weeks_status CHECK (status IN ('DRAFT', 'PUBLISHED'))
);

CREATE TABLE planning_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planning_week_id BIGINT NOT NULL REFERENCES planning_weeks(id),
    agent_id BIGINT NOT NULL REFERENCES planning_agents(id),
    shift_id BIGINT NOT NULL REFERENCES planning_shifts(id),
    shift_code VARCHAR(64) NOT NULL,
    shift_category VARCHAR(32) NOT NULL,
    assignment_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    paid_hours INTEGER NOT NULL,
    locked BOOLEAN NOT NULL DEFAULT FALSE,
    generated BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_planning_assignments_category CHECK (shift_category IN ('OPENING', 'CLOSING'))
);

CREATE INDEX idx_planning_assignments_date ON planning_assignments(assignment_date);
CREATE INDEX idx_planning_assignments_week ON planning_assignments(planning_week_id);
CREATE INDEX idx_agent_unavailability_date ON agent_unavailability(unavailable_date);

INSERT INTO planning_shifts (code, name, category, start_time, end_time, paid_hours, active) VALUES
('OPEN_03_12', 'Opening 03:00-12:00', 'OPENING', '03:00', '12:00', 8, TRUE),
('CLOSE_12_21', 'Closing 12:00-21:00', 'CLOSING', '12:00', '21:00', 8, TRUE),
('CLOSE_13_22', 'Late closing 13:00-22:00', 'CLOSING', '13:00', '22:00', 8, TRUE);

INSERT INTO planning_agents (full_name, email, active) VALUES
('Agent 01', 'agent01@test.com', TRUE),
('Agent 02', 'agent02@test.com', TRUE),
('Agent 03', 'agent03@test.com', TRUE),
('Agent 04', 'agent04@test.com', TRUE),
('Agent 05', 'agent05@test.com', TRUE),
('Agent 06', 'agent06@test.com', TRUE),
('Agent 07', 'agent07@test.com', TRUE),
('Agent 08', 'agent08@test.com', TRUE);
