CREATE TABLE IF NOT EXISTS planning_off_day_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planning_week_id BIGINT NOT NULL REFERENCES planning_weeks(id) ON DELETE CASCADE,
    agent_id BIGINT NOT NULL REFERENCES planning_agents(id),
    assignment_date DATE NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_planning_off_day_lock UNIQUE (planning_week_id, agent_id, assignment_date)
);

ALTER TABLE planning_weeks
    ADD COLUMN IF NOT EXISTS manually_overridden BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE planning_assignments
    ADD COLUMN IF NOT EXISTS manually_overridden BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS planning_override_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planning_week_id BIGINT NOT NULL REFERENCES planning_weeks(id) ON DELETE CASCADE,
    supervisor_identity VARCHAR(255) NOT NULL,
    overridden_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    agent_id BIGINT REFERENCES planning_agents(id),
    assignment_date DATE,
    previous_shift_id BIGINT REFERENCES planning_shifts(id),
    new_shift_id BIGINT REFERENCES planning_shifts(id),
    previous_value VARCHAR(64) NOT NULL,
    new_value VARCHAR(64) NOT NULL,
    violated_rules TEXT NOT NULL,
    override_reason TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_planning_off_day_locks_week ON planning_off_day_locks(planning_week_id);
CREATE INDEX IF NOT EXISTS idx_planning_override_audit_week ON planning_override_audit(planning_week_id);
CREATE INDEX IF NOT EXISTS idx_planning_override_audit_agent_date
    ON planning_override_audit(agent_id, assignment_date);
