CREATE TABLE planning_assignment_freezes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    day_of_week INT NOT NULL,
    shift_id BIGINT,
    start_date DATE NOT NULL,
    end_date DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_planning_assignment_freezes_active_range
    ON planning_assignment_freezes(active, start_date, end_date);

CREATE INDEX idx_planning_assignment_freezes_agent_day
    ON planning_assignment_freezes(agent_id, day_of_week, active);
