CREATE TABLE planning_telework_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL REFERENCES planning_agents(id),
    request_date DATE NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    reason VARCHAR(1000),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_planning_telework_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

CREATE TABLE planning_shift_swap_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_agent_id BIGINT NOT NULL REFERENCES planning_agents(id),
    target_agent_id BIGINT NOT NULL REFERENCES planning_agents(id),
    requester_date DATE NOT NULL,
    target_date DATE NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    reason VARCHAR(1000),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_planning_swap_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT ck_planning_swap_distinct_agents CHECK (requester_agent_id <> target_agent_id)
);

CREATE INDEX idx_planning_telework_agent_date
    ON planning_telework_requests(agent_id, request_date);

CREATE INDEX idx_planning_swap_requester
    ON planning_shift_swap_requests(requester_agent_id, requester_date);

CREATE INDEX idx_planning_swap_target
    ON planning_shift_swap_requests(target_agent_id, target_date);
