CREATE TABLE IF NOT EXISTS planning_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(80) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    action_url VARCHAR(500),
    target_email VARCHAR(255),
    target_role VARCHAR(80),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT ck_planning_notification_target CHECK (
        target_email IS NULL OR target_role IS NULL
    )
);

CREATE INDEX IF NOT EXISTS idx_planning_notifications_created
    ON planning_notifications(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_planning_notifications_email_unread
    ON planning_notifications(target_email, read_at);

CREATE INDEX IF NOT EXISTS idx_planning_notifications_role_unread
    ON planning_notifications(target_role, read_at);
