/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as QualityLabRouteImport } from './routes/quality-lab'
import { Route as PlanningViewRouteImport } from './routes/planning-view'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityLabRoute = QualityLabRouteImport.update({
  id: '/quality-lab',
  path: '/quality-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningViewRoute = PlanningViewRouteImport.update({
  id: '/planning-view',
  path: '/planning-view',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/planning': typeof PlanningRoute
  '/planning-view': typeof PlanningViewRoute
  '/quality-lab': typeof QualityLabRoute
  '/transport': typeof TransportRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/planning': typeof PlanningRoute
  '/planning-view': typeof PlanningViewRoute
  '/quality-lab': typeof QualityLabRoute
  '/transport': typeof TransportRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/planning': typeof PlanningRoute
  '/planning-view': typeof PlanningViewRoute
  '/quality-lab': typeof QualityLabRoute
  '/transport': typeof TransportRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/planning'
    | '/planning-view'
    | '/quality-lab'
    | '/transport'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/planning'
    | '/planning-view'
    | '/quality-lab'
    | '/transport'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/planning'
    | '/planning-view'
    | '/quality-lab'
    | '/transport'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PlanningRoute: typeof PlanningRoute
  PlanningViewRoute: typeof PlanningViewRoute
  QualityLabRoute: typeof QualityLabRoute
  TransportRoute: typeof TransportRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-lab': {
      id: '/quality-lab'
      path: '/quality-lab'
      fullPath: '/quality-lab'
      preLoaderRoute: typeof QualityLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning-view': {
      id: '/planning-view'
      path: '/planning-view'
      fullPath: '/planning-view'
      preLoaderRoute: typeof PlanningViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PlanningRoute: PlanningRoute,
  PlanningViewRoute: PlanningViewRoute,
  QualityLabRoute: QualityLabRoute,
  TransportRoute: TransportRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
