from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from datetime import date, datetime, time, timedelta
from pathlib import Path
from typing import Any, Iterable

import openpyxl
import psycopg2
from psycopg2.extras import execute_values


ACTIVE_STATUSES = ["NEW", "TODO", "ASSIGNED", "IN_PROGRESS", "WAITING_PROVIDER", "REOPENED"]
SHIFT_RE = re.compile(r"(\d{1,2})[:Hh](\d{2})\s*[-–]\s*(\d{1,2})[:Hh](\d{2})")


@dataclass(frozen=True)
class DbConfig:
    host: str
    port: int
    user: str
    password: str


def main() -> int:
    parser = argparse.ArgumentParser(description="Import CGI-Intranet Excel data into local PostgreSQL.")
    parser.add_argument("--data-dir", required=True)
    parser.add_argument("--host", required=True)
    parser.add_argument("--port", required=True, type=int)
    parser.add_argument("--user", required=True)
    parser.add_argument("--password", required=True)
    parser.add_argument("--auth-db", required=True)
    parser.add_argument("--ticket-db", required=True)
    parser.add_argument("--employee-db", required=True)
    parser.add_argument("--planning-db", required=True)
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    if not data_dir.exists():
        raise SystemExit(f"Data directory not found: {data_dir}")

    config = DbConfig(args.host, args.port, args.user, args.password)

    ensure_database(config, args.auth_db)
    ensure_database(config, args.ticket_db)
    ensure_database(config, args.employee_db)
    ensure_database(config, args.planning_db)

    with connect(config, args.ticket_db) as ticket_conn, connect(config, args.employee_db) as employee_conn, connect(config, args.planning_db) as planning_conn:
        ensure_ticket_schema(ticket_conn)
        ensure_employee_schema(employee_conn)
        ensure_planning_schema(planning_conn)

        user_ids = read_auth_user_ids(config, args.auth_db)
        employees = collect_employee_names(data_dir)
        import_employees(employee_conn, employees)
        import_planning(planning_conn, employees, data_dir)
        ticket_refs = import_tickets(ticket_conn, data_dir, user_ids)
        import_ticket_reporting(ticket_conn, data_dir)
        import_kpi_reporting(ticket_conn, data_dir)

        ticket_conn.commit()
        employee_conn.commit()
        planning_conn.commit()

    print("Excel import completed.")
    print(f"  employees/planning agents collected: {len(employees)}")
    print(f"  ticket references imported: {ticket_refs}")
    return 0


def connect(config: DbConfig, dbname: str):
    return psycopg2.connect(
        host=config.host,
        port=config.port,
        user=config.user,
        password=config.password,
        dbname=dbname,
    )


def ensure_database(config: DbConfig, dbname: str) -> None:
    conn = connect(config, "postgres")
    try:
        conn.autocommit = True
        with conn.cursor() as cursor:
            cursor.execute("select 1 from pg_database where datname = %s", (dbname,))
            if cursor.fetchone():
                return
            cursor.execute(f'create database "{dbname}"')
            print(f"Created database {dbname}")
    finally:
        conn.close()


def read_auth_user_ids(config: DbConfig, auth_db: str) -> dict[str, int]:
    ids = {"admin": 1, "manager": 2, "agent": 3}
    try:
        with connect(config, auth_db) as conn, conn.cursor() as cursor:
            cursor.execute(
                """
                select lower(email), id
                from user_profiles
                where lower(email) in ('pilote@cgi.local', 'superviseur@cgi.local', 'agent@cgi.local')
                """
            )
            for email, user_id in cursor.fetchall():
                if email == "pilote@cgi.local":
                    ids["admin"] = int(user_id)
                elif email == "superviseur@cgi.local":
                    ids["manager"] = int(user_id)
                elif email == "agent@cgi.local":
                    ids["agent"] = int(user_id)
    except Exception as exc:
        print(f"Auth user lookup skipped: {exc}")
    return ids


def ensure_ticket_schema(conn) -> None:
    with conn.cursor() as cursor:
        cursor.execute(
            """
            create table if not exists tickets (
                id bigint generated by default as identity primary key,
                reference varchar(32) not null unique,
                title varchar(180) not null,
                description varchar(5000) not null,
                status varchar(40) not null,
                type varchar(20) not null,
                category varchar(120),
                sub_category varchar(120),
                priority varchar(20) not null,
                criticality varchar(20) not null,
                requester_id bigint not null,
                assigned_user_id bigint,
                assigned_team_id bigint,
                department_id bigint,
                created_at timestamp without time zone not null,
                updated_at timestamp without time zone not null,
                assigned_at timestamp without time zone,
                started_at timestamp without time zone,
                resolved_at timestamp without time zone,
                closed_at timestamp without time zone,
                deleted boolean not null default false,
                deleted_at timestamp without time zone
            );

            create table if not exists sla_policies (
                id bigint generated by default as identity primary key,
                name varchar(160) not null,
                incident_type varchar(20) not null,
                priority varchar(20) not null,
                criticality varchar(20) not null,
                response_time_minutes integer not null,
                resolution_time_minutes integer not null,
                warning_threshold_percent integer not null,
                active boolean not null default true,
                created_at timestamp without time zone not null,
                updated_at timestamp without time zone not null
            );

            create table if not exists ticket_sla (
                id bigint generated by default as identity primary key,
                ticket_id bigint not null unique,
                policy_id bigint,
                response_deadline timestamp without time zone,
                resolution_deadline timestamp without time zone,
                first_response_at timestamp without time zone,
                resolved_at timestamp without time zone,
                response_status varchar(20) not null,
                resolution_status varchar(20) not null,
                global_status varchar(20) not null,
                elapsed_minutes bigint,
                remaining_minutes bigint,
                consumed_percentage double precision,
                breach_reason varchar(1000),
                last_calculated_at timestamp without time zone not null,
                escalation_level integer not null default 0,
                last_alert_at timestamp without time zone,
                last_escalation_at timestamp without time zone,
                created_at timestamp without time zone not null,
                updated_at timestamp without time zone not null
            );

            alter table ticket_sla add column if not exists policy_id bigint;
            alter table ticket_sla add column if not exists response_deadline timestamp without time zone;
            alter table ticket_sla add column if not exists resolution_deadline timestamp without time zone;
            alter table ticket_sla add column if not exists first_response_at timestamp without time zone;
            alter table ticket_sla add column if not exists resolved_at timestamp without time zone;
            alter table ticket_sla add column if not exists response_status varchar(20) not null default 'NOT_APPLICABLE';
            alter table ticket_sla add column if not exists resolution_status varchar(20) not null default 'NOT_APPLICABLE';
            alter table ticket_sla add column if not exists global_status varchar(20) not null default 'NOT_APPLICABLE';
            alter table ticket_sla add column if not exists elapsed_minutes bigint;
            alter table ticket_sla add column if not exists remaining_minutes bigint;
            alter table ticket_sla add column if not exists consumed_percentage double precision;
            alter table ticket_sla add column if not exists breach_reason varchar(1000);
            alter table ticket_sla add column if not exists last_calculated_at timestamp without time zone not null default now();
            alter table ticket_sla add column if not exists escalation_level integer not null default 0;
            alter table ticket_sla add column if not exists last_alert_at timestamp without time zone;
            alter table ticket_sla add column if not exists last_escalation_at timestamp without time zone;
            alter table ticket_sla add column if not exists created_at timestamp without time zone not null default now();
            alter table ticket_sla add column if not exists updated_at timestamp without time zone not null default now();

            create table if not exists excel_import_batches (
                id bigint generated by default as identity primary key,
                source_file varchar(255) not null,
                source_sheet varchar(120) not null,
                imported_at timestamp without time zone not null default now(),
                row_count integer not null default 0,
                unique (source_file, source_sheet)
            );

            create table if not exists excel_ticket_rejections (
                id bigint generated by default as identity primary key,
                source_row integer not null,
                responsible varchar(255),
                bannette varchar(255),
                rejection_reason varchar(1000),
                action varchar(1000),
                external_ticket_id varchar(80) not null,
                ticket_type varchar(120),
                title varchar(1000),
                impacting_service varchar(255),
                impacted_service varchar(255),
                digital_support varchar(255),
                categorization varchar(255),
                created_at timestamp without time zone,
                initial_priority varchar(80),
                priority varchar(80),
                resolution_bannette varchar(255),
                domain varchar(255),
                location varchar(255),
                status varchar(120),
                target_type varchar(120),
                target_state varchar(120),
                resolved_at timestamp without time zone,
                ttr_hours numeric,
                target_hours numeric,
                ttr_state varchar(120),
                reassignments integer,
                reminders integer,
                reopenings integer,
                ho_hno varchar(80),
                linked_incident varchar(120),
                odm_id varchar(120),
                imported_at timestamp without time zone not null default now(),
                unique (external_ticket_id)
            );

            create table if not exists excel_ticket_quality_checks (
                id bigint generated by default as identity primary key,
                source_file varchar(255) not null,
                source_sheet varchar(120) not null,
                source_row integer not null,
                external_ticket_id varchar(80) not null,
                title varchar(1000),
                description text,
                solution text,
                resolution_type varchar(255),
                request_summary text,
                actions_result text,
                politeness_formula text,
                solution_conformity varchar(120),
                resolution_type_conformity varchar(120),
                corrected_resolution_type varchar(255),
                supervisor_action text,
                supervisor_comment text,
                resolved_by varchar(255),
                assignment_group varchar(255),
                resolved_at timestamp without time zone,
                imported_at timestamp without time zone not null default now(),
                unique (source_file, source_sheet, external_ticket_id)
            );

            create table if not exists excel_publipostage_nps (
                id bigint generated by default as identity primary key,
                publication_date date,
                week_label varchar(80),
                bannette varchar(255),
                action_owner varchar(255),
                external_ticket_id varchar(80),
                email varchar(255),
                nps_score integer,
                imported_at timestamp without time zone not null default now(),
                unique (external_ticket_id, email, publication_date)
            );

            create table if not exists excel_kpi_agent_productivity (
                id bigint generated by default as identity primary key,
                source_file varchar(255) not null,
                source_sheet varchar(120) not null,
                source_row integer not null,
                agent_name varchar(255) not null,
                metric_name varchar(255) not null,
                metric_value numeric,
                imported_at timestamp without time zone not null default now(),
                unique (source_file, source_sheet, source_row, metric_name)
            );

            create table if not exists excel_kpi_action_plans (
                id bigint generated by default as identity primary key,
                source_file varchar(255) not null,
                source_sheet varchar(120) not null,
                source_row integer not null,
                main_action text,
                sub_actions text,
                details text,
                owner varchar(255),
                status varchar(255),
                start_date date,
                deadline date,
                service_level varchar(255),
                copil_action text,
                comments text,
                imported_at timestamp without time zone not null default now(),
                unique (source_file, source_sheet, source_row)
            );

            create table if not exists excel_knowledge_articles (
                id bigint generated by default as identity primary key,
                km_id varchar(120),
                article text,
                keywords text,
                service varchar(255),
                linked_ticket_count integer,
                created_on date,
                modified_on date,
                status varchar(120),
                km_number varchar(120),
                imported_at timestamp without time zone not null default now(),
                unique (km_id, km_number)
            );
            """
        )
        seed_sla_policies(cursor)


def seed_sla_policies(cursor) -> None:
    policies = [
        ("Incident critique", "INCIDENT", "URGENT", "CRITICAL", 15, 240, 80),
        ("Incident standard", "INCIDENT", "MEDIUM", "MEDIUM", 60, 480, 80),
        ("Demande faible priorité", "REQUEST", "LOW", "LOW", 240, 1440, 80),
    ]
    for policy in policies:
        cursor.execute(
            """
            insert into sla_policies (
                name, incident_type, priority, criticality, response_time_minutes,
                resolution_time_minutes, warning_threshold_percent, active, created_at, updated_at
            )
            select %s, %s, %s, %s, %s, %s, %s, true, now(), now()
            where not exists (select 1 from sla_policies where name = %s)
            """,
            (*policy, policy[0]),
        )


def ensure_employee_schema(conn) -> None:
    with conn.cursor() as cursor:
        cursor.execute(
            """
            create table if not exists employees (
                id bigint generated by default as identity primary key,
                user_keycloak_id varchar(255) unique,
                full_name varchar(255) not null,
                email varchar(255) unique,
                job_title varchar(255),
                department varchar(255) not null,
                bannette varchar(255),
                operational_status varchar(255),
                activity_status varchar(255),
                manager_keycloak_id varchar(255),
                phone varchar(255),
                address varchar(255),
                bio varchar(1000),
                profile_photo_url varchar(500),
                latitude double precision,
                longitude double precision,
                account_status varchar(40),
                availability_status varchar(40),
                created_at timestamp without time zone not null,
                updated_at timestamp without time zone not null
            );

            create table if not exists departments (
                id bigint generated by default as identity primary key,
                name varchar(255) not null unique,
                description varchar(1000),
                manager_keycloak_id varchar(255),
                active boolean not null default true,
                created_at timestamp without time zone not null,
                updated_at timestamp without time zone not null
            );
            """
        )


def ensure_planning_schema(conn) -> None:
    with conn.cursor() as cursor:
        cursor.execute(
            """
            create table if not exists planning_agents (
                id bigint generated by default as identity primary key,
                full_name varchar(255) not null,
                email varchar(255) unique,
                active boolean not null default true
            );

            create table if not exists planning_shifts (
                id bigint generated by default as identity primary key,
                code varchar(64) not null unique,
                name varchar(255) not null,
                category varchar(32) not null,
                start_time time not null,
                end_time time not null,
                paid_hours integer not null default 8,
                active boolean not null default true
            );

            create table if not exists planning_weeks (
                id bigint generated by default as identity primary key,
                week_start_date date not null unique,
                week_end_date date not null,
                status varchar(32) not null,
                generated_at timestamp without time zone not null
            );

            create table if not exists planning_assignments (
                id bigint generated by default as identity primary key,
                planning_week_id bigint not null references planning_weeks(id),
                agent_id bigint not null references planning_agents(id),
                shift_id bigint not null references planning_shifts(id),
                shift_code varchar(64) not null,
                shift_category varchar(32) not null,
                assignment_date date not null,
                start_time time not null,
                end_time time not null,
                paid_hours integer not null,
                locked boolean not null default false,
                generated boolean not null default true,
                manually_overridden boolean not null default false,
                lateness_minutes integer not null default 0,
                unique (planning_week_id, agent_id, assignment_date)
            );

            create unique index if not exists uk_planning_assignment_import
                on planning_assignments(planning_week_id, agent_id, assignment_date);

            create table if not exists agent_unavailability (
                id bigint generated by default as identity primary key,
                agent_id bigint not null references planning_agents(id),
                unavailable_date date not null,
                reason varchar(255) not null,
                unique (agent_id, unavailable_date)
            );
            """
        )


def collect_employee_names(data_dir: Path) -> dict[str, dict[str, str]]:
    employees: dict[str, dict[str, str]] = {}
    for filename in ["planning 1.xlsx", "KPI - DS Magasin (1) (1).xlsx", "tickets.xlsx"]:
        path = data_dir / filename
        if not path.exists():
            continue
        workbook = openpyxl.load_workbook(path, read_only=True, data_only=True)
        try:
            for sheet in workbook.worksheets:
                for row in sheet.iter_rows(values_only=True):
                    name = extract_agent_name(row)
                    if not name:
                        continue
                    normalized = normalize_name(name)
                    department = department_from_sheet(sheet.title)
                    employees.setdefault(normalized, {"full_name": name, "department": department, "bannette": department})
        finally:
            workbook.close()
    return employees


def extract_agent_name(row: Iterable[Any]) -> str | None:
    values = list(row)
    shift_indexes = [idx for idx, value in enumerate(values) if parse_shift(value)]
    if shift_indexes:
        first_shift = shift_indexes[0]
        for value in reversed(values[max(0, first_shift - 6):first_shift]):
            text = clean_text(value)
            if looks_like_person_name(text):
                return title_name(text)

    for value in values[:4]:
        text = clean_text(value)
        if looks_like_person_name(text):
            return title_name(text)
    return None


def looks_like_person_name(text: str) -> bool:
    if not text or len(text) < 5 or len(text) > 80:
        return False
    if parse_shift(text) or text.upper() in {"OFF", "BO", "FO", "SCO", "AGENT", "BANNETTES"}:
        return False
    if any(ch.isdigit() for ch in text):
        return False
    parts = [part for part in re.split(r"\s+", text.strip()) if part]
    return len(parts) >= 2 and all(len(part) > 1 for part in parts[:2])


def title_name(text: str) -> str:
    return " ".join(part.capitalize() if part.isupper() else part for part in text.split())


def department_from_sheet(sheet_name: str) -> str:
    upper = sheet_name.upper()
    if "BO" in upper:
        return "Back Office"
    if "FO" in upper:
        return "Front Office"
    if "SUP" in upper:
        return "Supervision"
    return "Support"


def import_employees(conn, employees: dict[str, dict[str, str]]) -> None:
    if not employees:
        return
    with conn.cursor() as cursor:
        departments = sorted({item["department"] for item in employees.values()})
        execute_values(
            cursor,
            """
            insert into departments (name, description, active, created_at, updated_at)
            values %s
            on conflict (name) do update set updated_at = excluded.updated_at, active = true
            """,
            [(dept, f"Département importé depuis les fichiers Excel.", True, datetime.now(), datetime.now()) for dept in departments],
        )

        rows = []
        for index, item in enumerate(sorted(employees.values(), key=lambda value: value["full_name"])):
            availability = ["AVAILABLE", "IN_COMMUNICATION", "BREAK", "LEAVE", "OFFLINE"][index % 5]
            rows.append(
                (
                    item["full_name"],
                    item["department"],
                    item["bannette"],
                    "Import Excel",
                    "Actif",
                    "ACTIVE",
                    availability,
                    datetime.now(),
                    datetime.now(),
                )
            )
        for row in rows:
            cursor.execute(
                """
                update employees
                set department = %s,
                    bannette = %s,
                    operational_status = %s,
                    activity_status = %s,
                    account_status = %s,
                    availability_status = %s,
                    updated_at = now()
                where lower(full_name) = lower(%s)
                """,
                (row[1], row[2], row[3], row[4], row[5], row[6], row[0]),
            )
            if cursor.rowcount == 0:
                cursor.execute(
                    """
                    insert into employees (
                        full_name, department, bannette, operational_status, activity_status,
                        account_status, availability_status, created_at, updated_at
                    )
                    values (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                    """,
                    row,
                )
    print(f"Imported/updated employees: {len(employees)}")


def import_planning(conn, employees: dict[str, dict[str, str]], data_dir: Path) -> None:
    shifts = [
        ("OPEN_03_12", "Ouverture 03:00-12:00", "OPENING", time(3, 0), time(12, 0), 8, True),
        ("NORMAL_05_14", "Shift 05:00-14:00", "NORMAL", time(5, 0), time(14, 0), 8, True),
        ("NORMAL_08_17", "Shift 08:00-17:00", "NORMAL", time(8, 0), time(17, 0), 8, True),
        ("NORMAL_09_18", "Shift 09:00-18:00", "NORMAL", time(9, 0), time(18, 0), 8, True),
        ("SCO_11_20", "SCO 11:00-20:00", "SCO", time(11, 0), time(20, 0), 8, True),
        ("CLOSE_12_21", "Fermeture 12:00-21:00", "CLOSING", time(12, 0), time(21, 0), 8, True),
        ("CLOSE_13_22", "Fermeture 13:00-22:00", "CLOSING", time(13, 0), time(22, 0), 8, True),
    ]
    monday = monday_of(date.today())
    with conn.cursor() as cursor:
        execute_values(
            cursor,
            """
            insert into planning_shifts (code, name, category, start_time, end_time, paid_hours, active)
            values %s
            on conflict (code) do update set
                name = excluded.name,
                category = excluded.category,
                start_time = excluded.start_time,
                end_time = excluded.end_time,
                paid_hours = excluded.paid_hours,
                active = true
            """,
            shifts,
        )
        for item in employees.values():
            cursor.execute(
                """
                update planning_agents set active = true where lower(full_name) = lower(%s)
                """,
                (item["full_name"],),
            )
            if cursor.rowcount == 0:
                cursor.execute(
                    "insert into planning_agents (full_name, email, active) values (%s, null, true)",
                    (item["full_name"],),
                )
        cursor.execute(
            """
            insert into planning_weeks (week_start_date, week_end_date, status, generated_at)
            values (%s, %s, 'PUBLISHED', now())
            on conflict (week_start_date) do update set status = 'PUBLISHED', generated_at = now()
            returning id
            """,
            (monday, monday + timedelta(days=6)),
        )
        week_id = cursor.fetchone()[0]
        cursor.execute("select id, full_name from planning_agents where active = true order by full_name limit 40")
        agents = cursor.fetchall()
        shift_by_code = get_shift_ids(cursor)
        assignments = []
        for agent_index, (agent_id, _full_name) in enumerate(agents):
            for day_index in range(5):
                code = shifts[(agent_index + day_index) % len(shifts)][0]
                shift_id, category, start, end, paid = shift_by_code[code]
                assignments.append((week_id, agent_id, shift_id, code, category, monday + timedelta(days=day_index), start, end, paid, False, True, False, 0))
        if assignments:
            execute_values(
                cursor,
                """
                insert into planning_assignments (
                    planning_week_id, agent_id, shift_id, shift_code, shift_category,
                    assignment_date, start_time, end_time, paid_hours, locked, generated,
                    manually_overridden, lateness_minutes
                )
                values %s
                on conflict (planning_week_id, agent_id, assignment_date) do update set
                    shift_id = excluded.shift_id,
                    shift_code = excluded.shift_code,
                    shift_category = excluded.shift_category,
                    start_time = excluded.start_time,
                    end_time = excluded.end_time,
                    paid_hours = excluded.paid_hours,
                    generated = true
                """
                ,
                assignments,
            )
    print(f"Imported planning agents/assignments: {len(employees)} agents, {len(assignments)} assignments")


def get_shift_ids(cursor) -> dict[str, tuple[int, str, time, time, int]]:
    cursor.execute("select id, code, category, start_time, end_time, paid_hours from planning_shifts")
    return {code: (shift_id, category, start, end, paid) for shift_id, code, category, start, end, paid in cursor.fetchall()}


def import_tickets(conn, data_dir: Path, user_ids: dict[str, int]) -> int:
    path = data_dir / "tickets.xlsx"
    if not path.exists():
        return 0
    workbook = openpyxl.load_workbook(path, read_only=True, data_only=True)
    try:
        sheet = workbook["Rejets"]
        headers = row_headers(next(sheet.iter_rows(min_row=1, max_row=1, values_only=True)))
        rows = []
        for source_row, row in enumerate(sheet.iter_rows(min_row=2, values_only=True), start=2):
            record = dict(zip(headers, row))
            external_id = clean_text(record.get("ID TICKET"))
            if not external_id:
                continue
            reference = reference_from_external_id(external_id)
            created_at = as_datetime(record.get("DATE CREATION")) or datetime.now() - timedelta(days=source_row % 30)
            resolved_at = as_datetime(record.get("DATE RESOLUTION"))
            status = map_ticket_status(record.get("STATUT"), resolved_at, source_row)
            priority = map_priority(record.get("PRIORITE") or record.get("PRIORITE INITIALE"))
            criticality = map_criticality(priority, record.get("ETAT TTR"))
            assigned = user_ids["manager"] if status in {"ASSIGNED", "IN_PROGRESS", "WAITING_PROVIDER", "RESOLVED", "CLOSED"} else None
            started_at = created_at + timedelta(minutes=15) if status in {"IN_PROGRESS", "RESOLVED", "CLOSED"} else None
            rows.append(
                (
                    reference,
                    truncate(clean_text(record.get("TITRE")) or f"Ticket importé {external_id}", 180),
                    truncate(clean_text(record.get("Motif du rejet")) or clean_text(record.get("CATEGORISATION")) or "Ticket importé depuis Excel.", 5000),
                    status,
                    map_ticket_type(record.get("TYPE")),
                    truncate(clean_text(record.get("SERVICE IMPACTANT")) or clean_text(record.get("Bannette")) or "Import Excel", 120),
                    truncate(clean_text(record.get("CATEGORISATION")) or clean_text(record.get("DOMAINE")), 120),
                    priority,
                    criticality,
                    user_ids["admin"],
                    assigned,
                    None,
                    None,
                    created_at,
                    resolved_at or datetime.now(),
                    created_at + timedelta(minutes=5) if assigned else None,
                    started_at,
                    resolved_at if status in {"RESOLVED", "CLOSED"} else None,
                    resolved_at if status == "CLOSED" else None,
                    False,
                    None,
                    source_row,
                    record,
                )
            )
            if len(rows) >= 1200:
                break
    finally:
        workbook.close()

    with conn.cursor() as cursor:
        execute_values(
            cursor,
            """
            insert into tickets (
                reference, title, description, status, type, category, sub_category, priority, criticality,
                requester_id, assigned_user_id, assigned_team_id, department_id, created_at, updated_at,
                assigned_at, started_at, resolved_at, closed_at, deleted, deleted_at
            )
            values %s
            on conflict (reference) do update set
                title = excluded.title,
                description = excluded.description,
                status = excluded.status,
                type = excluded.type,
                category = excluded.category,
                sub_category = excluded.sub_category,
                priority = excluded.priority,
                criticality = excluded.criticality,
                assigned_user_id = excluded.assigned_user_id,
                updated_at = excluded.updated_at,
                assigned_at = excluded.assigned_at,
                started_at = excluded.started_at,
                resolved_at = excluded.resolved_at,
                closed_at = excluded.closed_at,
                deleted = false,
                deleted_at = null
            """,
            [row[:21] for row in rows],
            page_size=200,
        )
        upsert_ticket_sla(cursor, rows)
    print(f"Imported tickets into operational table: {len(rows)}")
    return len(rows)


def upsert_ticket_sla(cursor, rows: list[tuple[Any, ...]]) -> None:
    for row in rows:
        reference = row[0]
        status = row[3]
        priority = row[7]
        criticality = row[8]
        created_at = row[13]
        resolved_at = row[17]
        source = row[22]
        sla_status = map_sla_status(status, source)
        response_deadline = created_at + timedelta(minutes=15 if priority == "URGENT" else 60)
        resolution_deadline = created_at + timedelta(hours=4 if criticality == "CRITICAL" else 8)
        first_response_at = row[15] or (created_at + timedelta(minutes=10))
        consumed = 100.0 if sla_status == "BREACHED" else 85.0 if sla_status == "AT_RISK" else 40.0
        remaining = -60 if sla_status == "BREACHED" else 45 if sla_status == "AT_RISK" else 240
        cursor.execute(
            """
            insert into ticket_sla (
                ticket_id, policy_id, response_deadline, resolution_deadline, first_response_at,
                resolved_at, response_status, resolution_status, global_status, elapsed_minutes,
                remaining_minutes, consumed_percentage, breach_reason, last_calculated_at,
                escalation_level, last_alert_at, last_escalation_at, created_at, updated_at
            )
            select id, null, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, now(), %s, null, null, now(), now()
            from tickets where reference = %s
            on conflict (ticket_id) do update set
                response_deadline = excluded.response_deadline,
                resolution_deadline = excluded.resolution_deadline,
                first_response_at = excluded.first_response_at,
                resolved_at = excluded.resolved_at,
                response_status = excluded.response_status,
                resolution_status = excluded.resolution_status,
                global_status = excluded.global_status,
                elapsed_minutes = excluded.elapsed_minutes,
                remaining_minutes = excluded.remaining_minutes,
                consumed_percentage = excluded.consumed_percentage,
                breach_reason = excluded.breach_reason,
                last_calculated_at = now(),
                updated_at = now()
            """,
            (
                response_deadline,
                resolution_deadline,
                first_response_at,
                resolved_at,
                sla_status,
                sla_status,
                sla_status,
                int((datetime.now() - created_at).total_seconds() // 60),
                remaining,
                consumed,
                "Import Excel: TTR dépassé" if sla_status == "BREACHED" else None,
                1 if sla_status == "BREACHED" else 0,
                reference,
            ),
        )


def import_ticket_reporting(conn, data_dir: Path) -> None:
    path = data_dir / "tickets.xlsx"
    if not path.exists():
        return
    workbook = openpyxl.load_workbook(path, read_only=True, data_only=True)
    try:
        import_rejections_reporting(conn, workbook, path.name)
        import_quality_reporting(conn, workbook, path.name)
        import_publipostage(conn, workbook)
    finally:
        workbook.close()

    casa = data_dir / "CGI_CASA_06_04_2026_au_12_04_2026.xlsx"
    if casa.exists():
        workbook = openpyxl.load_workbook(casa, read_only=True, data_only=True)
        try:
            import_casa_quality(conn, workbook, casa.name)
        finally:
            workbook.close()


def import_rejections_reporting(conn, workbook, source_file: str) -> None:
    if "Rejets" not in workbook.sheetnames:
        return
    sheet = workbook["Rejets"]
    headers = row_headers(next(sheet.iter_rows(min_row=1, max_row=1, values_only=True)))
    rows_by_ticket = {}
    for source_row, row in enumerate(sheet.iter_rows(min_row=2, values_only=True), start=2):
        record = dict(zip(headers, row))
        external_id = clean_text(record.get("ID TICKET"))
        if not external_id:
            continue
        rows_by_ticket[external_id] = (
                source_row,
                clean_text(record.get("Résponsable")),
                clean_text(record.get("Bannette")),
                clean_text(record.get("Motif du rejet")),
                clean_text(record.get("Action")),
                external_id,
                clean_text(record.get("TYPE")),
                clean_text(record.get("TITRE")),
                clean_text(record.get("SERVICE IMPACTANT")),
                clean_text(record.get("SERVICE IMPACTE")),
                clean_text(record.get("DIGITAL SUPPORT")),
                clean_text(record.get("CATEGORISATION")),
                as_datetime(record.get("DATE CREATION")),
                clean_text(record.get("PRIORITE INITIALE")),
                clean_text(record.get("PRIORITE")),
                clean_text(record.get("BANNETTE RESOLUTION")),
                clean_text(record.get("DOMAINE")),
                clean_text(record.get("EMPLACEMENT")),
                clean_text(record.get("STATUT")),
                clean_text(record.get("TYPE CIBLE")),
                clean_text(record.get("ETAT CIBLE")),
                as_datetime(record.get("DATE RESOLUTION")),
                as_number(record.get("DUREE TTR (H)")),
                as_number(record.get("CIBLE (H)")),
                clean_text(record.get("ETAT TTR")),
                as_int(record.get("REAFFECTATIONS")),
                as_int(record.get("RELANCES")),
                as_int(record.get("REOUVERTURES")),
                clean_text(record.get("HO HNO")),
                clean_text(record.get("INCIDENT LIE")),
                clean_text(record.get("ID ODM")),
        )
    rows = list(rows_by_ticket.values())
    with conn.cursor() as cursor:
        execute_values(
            cursor,
            """
            insert into excel_ticket_rejections (
                source_row, responsible, bannette, rejection_reason, action, external_ticket_id,
                ticket_type, title, impacting_service, impacted_service, digital_support,
                categorization, created_at, initial_priority, priority, resolution_bannette,
                domain, location, status, target_type, target_state, resolved_at, ttr_hours,
                target_hours, ttr_state, reassignments, reminders, reopenings, ho_hno,
                linked_incident, odm_id
            )
            values %s
            on conflict (external_ticket_id) do update set
                responsible = excluded.responsible,
                bannette = excluded.bannette,
                rejection_reason = excluded.rejection_reason,
                action = excluded.action,
                status = excluded.status,
                resolved_at = excluded.resolved_at,
                imported_at = now()
            """,
            rows,
            page_size=500,
        )
        upsert_import_batch(cursor, source_file, "Rejets", len(rows))
    print(f"Imported ticket rejection reporting rows: {len(rows)}")


def import_quality_reporting(conn, workbook, source_file: str) -> None:
    if "Picking" not in workbook.sheetnames:
        return
    sheet = workbook["Picking"]
    headers = row_headers(next(sheet.iter_rows(min_row=1, max_row=1, values_only=True)))
    rows_by_ticket = {}
    for source_row, row in enumerate(sheet.iter_rows(min_row=2, values_only=True), start=2):
        record = dict(zip(headers, row))
        external_id = clean_text(record.get("ID Ticket"))
        if not external_id:
            continue
        rows_by_ticket[external_id] = (
                source_file,
                "Picking",
                source_row,
                external_id,
                clean_text(record.get("Titre")),
                clean_text(record.get("Description")),
                clean_text(record.get("Solution")),
                clean_text(record.get("Type de résolution")),
                clean_text(record.get("Synthèse de la demande")),
                clean_text(record.get("Actions / Résultat")),
                clean_text(record.get("Formule de politesse")),
                clean_text(record.get("Conformité Solution")),
                clean_text(record.get("Conformité Type de Résolution")),
                clean_text(record.get("Correction Type de résolution")),
                clean_text(record.get("Actions Sup")),
                clean_text(record.get("Commentaire Sup")),
                None,
                None,
                None,
        )
    rows = list(rows_by_ticket.values())
    with conn.cursor() as cursor:
        execute_values(
            cursor,
            """
            insert into excel_ticket_quality_checks (
                source_file, source_sheet, source_row, external_ticket_id, title, description,
                solution, resolution_type, request_summary, actions_result, politeness_formula,
                solution_conformity, resolution_type_conformity, corrected_resolution_type,
                supervisor_action, supervisor_comment, resolved_by, assignment_group, resolved_at
            )
            values %s
            on conflict (source_file, source_sheet, external_ticket_id) do update set
                title = excluded.title,
                solution = excluded.solution,
                solution_conformity = excluded.solution_conformity,
                supervisor_comment = excluded.supervisor_comment,
                imported_at = now()
            """,
            rows,
            page_size=500,
        )
        upsert_import_batch(cursor, source_file, "Picking", len(rows))
    print(f"Imported ticket quality rows: {len(rows)}")


def import_casa_quality(conn, workbook, source_file: str) -> None:
    sheet = workbook.worksheets[0]
    row_iter = sheet.iter_rows(values_only=True)
    header = None
    header_row_index = 0
    for index, row in enumerate(row_iter, start=1):
        values = row_headers(row)
        if "ID" in values and "Titre" in values:
            header = values
            header_row_index = index
            break
    if not header:
        return
    rows_by_ticket = {}
    for source_row, row in enumerate(sheet.iter_rows(min_row=header_row_index + 1, values_only=True), start=header_row_index + 1):
        record = dict(zip(header, row))
        external_id = clean_text(record.get("ID"))
        if not external_id:
            continue
        rows_by_ticket[external_id] = (
                source_file,
                sheet.title,
                source_row,
                external_id,
                clean_text(record.get("Titre")),
                clean_text(record.get("Description")),
                clean_text(record.get("Solution")),
                clean_text(record.get("Type de résolution")),
                clean_text(record.get("Synthèse de la demande")),
                clean_text(record.get("Actions / Résultat")),
                clean_text(record.get("Formule de politesse")),
                clean_text(record.get("Conformité Solution")),
                clean_text(record.get("Conformité Type de Résolution")),
                clean_text(record.get("Correction Type de résolution")),
                None,
                None,
                clean_text(record.get("Résolu par Nom")),
                clean_text(record.get("Groupe d'affectation Nom")),
                as_datetime(record.get("Date/Heure de résolution")),
        )
    rows = list(rows_by_ticket.values())
    with conn.cursor() as cursor:
        execute_values(
            cursor,
            """
            insert into excel_ticket_quality_checks (
                source_file, source_sheet, source_row, external_ticket_id, title, description,
                solution, resolution_type, request_summary, actions_result, politeness_formula,
                solution_conformity, resolution_type_conformity, corrected_resolution_type,
                supervisor_action, supervisor_comment, resolved_by, assignment_group, resolved_at
            )
            values %s
            on conflict (source_file, source_sheet, external_ticket_id) do update set
                title = excluded.title,
                solution = excluded.solution,
                resolved_by = excluded.resolved_by,
                assignment_group = excluded.assignment_group,
                imported_at = now()
            """,
            rows,
            page_size=500,
        )
        upsert_import_batch(cursor, source_file, sheet.title, len(rows))
    print(f"Imported CASA quality rows: {len(rows)}")


def import_publipostage(conn, workbook) -> None:
    if "Publipostage" not in workbook.sheetnames:
        return
    sheet = workbook["Publipostage"]
    headers = row_headers(next(sheet.iter_rows(min_row=1, max_row=1, values_only=True)))
    rows = []
    for row in sheet.iter_rows(min_row=2, values_only=True):
        record = dict(zip(headers, row))
        external_id = clean_text(record.get("N° Ticket"))
        email = clean_text(record.get("Adresse mail"))
        if not external_id and not email:
            continue
        rows.append(
            (
                as_date(record.get("Date Publi")),
                clean_text(record.get("Semaine")),
                clean_text(record.get("Bannette")),
                clean_text(record.get("Résponsable action")),
                external_id,
                email,
                as_int(record.get("Note NPS")),
            )
        )
    with conn.cursor() as cursor:
        execute_values(
            cursor,
            """
            insert into excel_publipostage_nps (
                publication_date, week_label, bannette, action_owner, external_ticket_id, email, nps_score
            )
            values %s
            on conflict (external_ticket_id, email, publication_date) do update set
                bannette = excluded.bannette,
                action_owner = excluded.action_owner,
                nps_score = excluded.nps_score,
                imported_at = now()
            """,
            rows,
            page_size=500,
        )
        upsert_import_batch(cursor, "tickets.xlsx", "Publipostage", len(rows))
    print(f"Imported NPS mail rows: {len(rows)}")


def import_kpi_reporting(conn, data_dir: Path) -> None:
    path = data_dir / "KPI - DS Magasin (1) (1).xlsx"
    if not path.exists():
        return
    workbook = openpyxl.load_workbook(path, read_only=True, data_only=True)
    try:
        import_action_plans(conn, workbook, path.name)
        import_knowledge_articles(conn, workbook)
        import_productivity_sample(conn, workbook, path.name)
    finally:
        workbook.close()


def import_action_plans(conn, workbook, source_file: str) -> None:
    rows = []
    target_sheets = [name for name in workbook.sheetnames if name.startswith("PA-")]
    for sheet_name in target_sheets:
        sheet = workbook[sheet_name]
        header = row_headers(next(sheet.iter_rows(min_row=1, max_row=1, values_only=True)))
        if not any("Action" in item for item in header):
            continue
        for source_row, row in enumerate(sheet.iter_rows(min_row=2, values_only=True), start=2):
            record = dict(zip(header, row))
            main_action = clean_text(record.get("Action principale") or record.get("Action"))
            if not main_action:
                continue
            rows.append(
                (
                    source_file,
                    sheet_name,
                    source_row,
                    main_action,
                    clean_text(record.get("Sous-action(s)")),
                    clean_text(record.get("Détails du plan d’action")),
                    clean_text(record.get("Porteur d’action") or record.get("Responsable")),
                    clean_text(record.get("Statut / Mise en place") or record.get("État")),
                    as_date(record.get("Date de démarrage") or record.get("Date Début")),
                    as_date(record.get("Deadline") or record.get("Date Fin")),
                    clean_text(record.get("Niveau de service")),
                    clean_text(record.get("Action COPIL")),
                    clean_text(record.get("Commentaires") or record.get("Commentaire/Avancement/ROI")),
                )
            )
    if rows:
        with conn.cursor() as cursor:
            execute_values(
                cursor,
                """
                insert into excel_kpi_action_plans (
                    source_file, source_sheet, source_row, main_action, sub_actions, details,
                    owner, status, start_date, deadline, service_level, copil_action, comments
                )
                values %s
                on conflict (source_file, source_sheet, source_row) do update set
                    main_action = excluded.main_action,
                    status = excluded.status,
                    comments = excluded.comments,
                    imported_at = now()
                """,
                rows,
                page_size=200,
            )
    print(f"Imported KPI action plans: {len(rows)}")


def import_knowledge_articles(conn, workbook) -> None:
    if "KM" not in workbook.sheetnames:
        return
    sheet = workbook["KM"]
    headers = row_headers(next(sheet.iter_rows(min_row=1, max_row=1, values_only=True)))
    rows_by_key = {}
    for row in sheet.iter_rows(min_row=2, values_only=True):
        record = dict(zip(headers, row))
        km_id = clean_text(record.get("ID KM"))
        article = clean_text(record.get("Article"))
        if not km_id and not article:
            continue
        km_number = clean_text(record.get("N° KM"))
        fallback_key = slug(article[:80] or f"row-{len(rows_by_key) + 1}")
        stored_km_id = km_id or f"ARTICLE-{fallback_key}"
        stored_km_number = km_number or f"KM-{fallback_key}"
        key = (stored_km_id, stored_km_number)
        rows_by_key[key] = (
                stored_km_id,
                article,
                clean_text(record.get("Mots clefs")),
                clean_text(record.get("Service")),
                as_int(record.get("N° Tickets rattachés (5ans)")),
                as_date(record.get("Date de création")),
                as_date(record.get("Date de modification")),
                clean_text(record.get("Statut")),
                stored_km_number,
        )
    rows = list(rows_by_key.values())
    with conn.cursor() as cursor:
        execute_values(
            cursor,
            """
            insert into excel_knowledge_articles (
                km_id, article, keywords, service, linked_ticket_count, created_on, modified_on, status, km_number
            )
            values %s
            on conflict (km_id, km_number) do update set
                article = excluded.article,
                keywords = excluded.keywords,
                status = excluded.status,
                imported_at = now()
            """,
            rows,
            page_size=200,
        )
        upsert_import_batch(cursor, "KPI - DS Magasin (1) (1).xlsx", "KM", len(rows))
    print(f"Imported KM articles: {len(rows)}")


def import_productivity_sample(conn, workbook, source_file: str) -> None:
    if "W&M-DS.M-Prod." not in workbook.sheetnames:
        return
    sheet = workbook["W&M-DS.M-Prod."]
    header_row = 25
    headers = row_headers(next(sheet.iter_rows(min_row=header_row, max_row=header_row, values_only=True)))
    metric_names = headers[1:12]
    rows = []
    for source_row, row in enumerate(sheet.iter_rows(min_row=header_row + 1, values_only=True), start=header_row + 1):
        agent = clean_text(row[0] if row else None)
        if not looks_like_person_name(agent):
            continue
        for index, metric in enumerate(metric_names, start=1):
            if not metric:
                continue
            value = as_number(row[index] if index < len(row) else None)
            if value is None:
                continue
            rows.append((source_file, sheet.title, source_row, title_name(agent), metric, value))
    with conn.cursor() as cursor:
        execute_values(
            cursor,
            """
            insert into excel_kpi_agent_productivity (
                source_file, source_sheet, source_row, agent_name, metric_name, metric_value
            )
            values %s
            on conflict (source_file, source_sheet, source_row, metric_name) do update set
                agent_name = excluded.agent_name,
                metric_value = excluded.metric_value,
                imported_at = now()
            """,
            rows,
            page_size=500,
        )
        upsert_import_batch(cursor, source_file, sheet.title, len(rows))
    print(f"Imported KPI productivity sample rows: {len(rows)}")


def upsert_import_batch(cursor, source_file: str, source_sheet: str, row_count: int) -> None:
    cursor.execute(
        """
        insert into excel_import_batches (source_file, source_sheet, imported_at, row_count)
        values (%s, %s, now(), %s)
        on conflict (source_file, source_sheet) do update set imported_at = now(), row_count = excluded.row_count
        """,
        (source_file, source_sheet, row_count),
    )


def row_headers(row: Iterable[Any]) -> list[str]:
    headers = []
    seen = defaultdict(int)
    for index, value in enumerate(row):
        header = clean_text(value) or f"column_{index + 1}"
        seen[header] += 1
        if seen[header] > 1:
            header = f"{header}__{seen[header]}"
        headers.append(header)
    return headers


def map_ticket_status(value: Any, resolved_at: datetime | None, source_row: int) -> str:
    text = clean_text(value).upper()
    if resolved_at or "RESOL" in text or "CLOS" in text or "CLOT" in text:
        return "RESOLVED"
    if "ANNUL" in text or "CANCEL" in text:
        return "CANCELLED"
    return ACTIVE_STATUSES[source_row % len(ACTIVE_STATUSES)]


def map_priority(value: Any) -> str:
    text = clean_text(value).upper()
    if any(token in text for token in ["P1", "URG", "CRIT", "HAUTE", "HIGH"]):
        return "URGENT"
    if any(token in text for token in ["P2", "MOY", "MED"]):
        return "HIGH"
    if any(token in text for token in ["P3", "LOW", "BASSE", "FAIBLE"]):
        return "LOW"
    return "MEDIUM"


def map_criticality(priority: str, ttr_state: Any) -> str:
    text = clean_text(ttr_state).upper()
    if "DEP" in text or "KO" in text or priority == "URGENT":
        return "CRITICAL"
    if priority == "HIGH":
        return "HIGH"
    if priority == "LOW":
        return "LOW"
    return "MEDIUM"


def map_ticket_type(value: Any) -> str:
    text = clean_text(value).upper()
    if "CHANGE" in text:
        return "CHANGE"
    if "PROBLEM" in text or "PROBLEME" in text:
        return "PROBLEM"
    if "DEMANDE" in text or "REQUEST" in text:
        return "REQUEST"
    return "INCIDENT"


def map_sla_status(status: str, record: dict[str, Any]) -> str:
    ttr = clean_text(record.get("ETAT TTR")).upper()
    if "DEP" in ttr or "KO" in ttr:
        return "BREACHED"
    if status in {"NEW", "TODO", "ASSIGNED", "IN_PROGRESS"}:
        return "AT_RISK"
    if status in {"WAITING_PROVIDER", "WAITING_REQUESTER", "WAITING_MANAGER_VALIDATION"}:
        return "PAUSED"
    return "RESPECTED"


def reference_from_external_id(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_-]+", "-", value.strip())
    return truncate(f"XLS-{cleaned}", 32)


def parse_shift(value: Any) -> tuple[str, time, time] | None:
    text = clean_text(value)
    if not text:
        return None
    if "OFF" == text.upper():
        return ("OFF", time(0, 0), time(0, 0))
    if "SCO" in text.upper() or "11H-20H" in text.upper():
        return ("SCO_11_20", time(11, 0), time(20, 0))
    match = SHIFT_RE.search(text)
    if not match:
        return None
    start_hour, start_minute, end_hour, end_minute = [int(part) for part in match.groups()]
    code = f"NORMAL_{start_hour:02d}_{end_hour:02d}"
    if start_hour == 3:
        code = "OPEN_03_12"
    elif start_hour == 5:
        code = "NORMAL_05_14"
    elif start_hour == 8:
        code = "NORMAL_08_17"
    elif start_hour == 9:
        code = "NORMAL_09_18"
    elif start_hour == 12:
        code = "CLOSE_12_21"
    elif start_hour == 13:
        code = "CLOSE_13_22"
    return (code, time(start_hour, start_minute), time(end_hour, end_minute))


def monday_of(value: date) -> date:
    return value - timedelta(days=value.weekday())


def clean_text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, datetime):
        return value.isoformat(sep=" ")
    text = str(value).replace("\n", " ").replace("\t", " ").strip()
    return re.sub(r"\s+", " ", text)


def normalize_name(value: str) -> str:
    return clean_text(value).casefold()


def truncate(value: str, max_length: int) -> str:
    return value[:max_length] if value else value


def slug(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9]+", "-", value.strip()).strip("-").upper()
    return truncate(cleaned or "UNKNOWN", 80)


def as_datetime(value: Any) -> datetime | None:
    if isinstance(value, datetime):
        return value.replace(tzinfo=None)
    if isinstance(value, date):
        return datetime.combine(value, time.min)
    text = clean_text(value)
    if not text:
        return None
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d", "%d/%m/%Y %H:%M:%S", "%d/%m/%Y"):
        try:
            return datetime.strptime(text, fmt)
        except ValueError:
            pass
    return None


def as_date(value: Any) -> date | None:
    parsed = as_datetime(value)
    return parsed.date() if parsed else None


def as_number(value: Any) -> float | None:
    if value is None or value == "":
        return None
    if isinstance(value, (int, float)):
        return float(value)
    text = clean_text(value).replace("%", "").replace(",", ".")
    try:
        return float(text)
    except ValueError:
        return None


def as_int(value: Any) -> int | None:
    number = as_number(value)
    return int(number) if number is not None else None


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except psycopg2.OperationalError as exc:
        print(f"PostgreSQL connection failed: {exc}", file=sys.stderr)
        print("Start the local PostgreSQL stack first, then rerun scripts\\import-excel-data.ps1.", file=sys.stderr)
        raise SystemExit(2)
