server {
  listen 80;
  server_name _;

  location = /health {
    access_log off;
    add_header Content-Type text/plain;
    return 200 "ok\n";
  }

  location /kpi-app/ {
    alias /usr/share/nginx/html/kpi-app/;
    try_files $uri $uri/ /kpi-app/index.html;
  }

  location = / {
    return 302 /kpi-app/;
  }
}
